Fronted.sign up
404-Team-name-not-found/NotAGoodTaskManagement pull request #35
Opened 2022-01-04 20:06 UTC by BarSh0

2022-01-04 21:53 UTC, amnon3234 requested changes
overall, nice work !

2022-01-04 21:53 UTC, amnon3234 commented on client/Roots/root.scss
> +
Like we said in the meeting, or only css or only sass

2022-01-04 21:53 UTC, amnon3234 commented on client/Roots/root.scss
> +    --1:#B5AFA4;
what is 1 ? maybe a more meaning full name would be more readable

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.css
> +	box-sizing: border-box;
remove spaces

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.css
> +:root {
its a duplicate from the root.scss file ?

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.css
> +body {
enter between selectors : 
```
.className {
}
--space--
.className2 {
}
```

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.css
> +  color: var(--bg-color);
use 2 indentation or 4 indention for the entire project. and in general stay consistent with what you are choosing

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.css
> +body {
is body relevant to the signin component ? 
maybe you should open more css files. one called root with the vars and body style
and for each component a file with its own relevant classes and style

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.css
> +  color: var(--bg-color);
( recommending on 2 )

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.js
> +
to much space

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.js
> +	checkInputs();
checkInputs declare can appear bellow the call because of hoisting, however it is more readable to first declare the function and then use it

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.js
> +function checkInputs() {
function which is not exported from the file => please use const declaration instead of the function declaration

2022-01-04 21:53 UTC, amnon3234 commented on client/Sign-Up/signin.js
> +function isEmail(email) {
same for all the functions, please declare and than call

2022-01-05 08:43 UTC, BarSh0 commented on client/Sign-Up/signin.css
> +:root {
Yes I will change it because I did not know how to IMPORT the file, now I know

2022-01-05 08:44 UTC, BarSh0 commented on client/Sign-Up/signin.css
> +body {
true I will do so

2022-01-05 10:34 UTC, merged